[build]
command = "npm run build"
publish = ".next"

[[redirects]]
from = "/webhooks/twilio"
to = "/.netlify/functions/webhooks_twilio"
status = 200

[functions]
node_bundler = "esbuild"

[template.environment]
DATABASE_URL = "Database Connection String"
TWILIO_AUTH_TOKEN = "Twilio Auth Token"
NEXT_PUBLIC_TWILIO_NUMBER = "Twilio Phone number"
PUSHER_APP_ID = "Pusher App ID"
NEXT_PUBLIC_PUSHER_KEY = "Pusher Key"
NEXT_PUBLIC_PUSHER_CLUSTER = "Pusher Cluster"

[[plugins]]
package = "@netlify/plugin-nextjs"
